# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b0ea29559b483510dc285e2d33f43e3995ee163ddd797d2c1ea104113dd8462e4d22db3558c4931ea7ba6075501cfc9fa7ad385249f0e3cb0f584a8b432711

test:
  secret_key_base: 84e6bcb1589bddaefe0022f38f3511699c01666a04bbd7850828340d9b8f4714d15e644c1b16b2acbd35bd24ca365cf0b182272509d417f416fb49e81400274c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
